export type EcosystemPartner = {
  name: string;
  /** Light-colored mark for the dark site theme. */
  logo: string;
  /** Dark-ink mark for the light site theme. */
  logoLight: string;
  width: number;
  height: number;
  tone: "dark" | "light";
  logoShape?: "wide" | "icon" | "tall";
  showName?: boolean;
  monochromeOnLight?: boolean;
};

export const ECOSYSTEM_PARTNERS: readonly EcosystemPartner[] = [
  {
    name: "Anastasia Labs",
    logo: "/ecosystem/anastasia-labs.svg",
    logoLight: "/ecosystem/anastasia-labs.svg",
    width: 2000,
    height: 464,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Sundae Labs",
    logo: "/ecosystem/sundae-labs-dark.png",
    logoLight: "/ecosystem/sundae-labs.png",
    width: 1143,
    height: 195,
    tone: "dark",
    logoShape: "wide",
  },
  {
    name: "Input Output Global",
    logo: "/ecosystem/input-output.svg",
    logoLight: "/ecosystem/input-output-light.svg",
    width: 240,
    height: 31,
    tone: "dark",
    logoShape: "wide",
  },
  {
    name: "VIA Labs",
    logo: "/ecosystem/via-labs.svg",
    logoLight: "/ecosystem/via-labs.svg",
    width: 140,
    height: 26,
    tone: "dark",
    logoShape: "wide",
    monochromeOnLight: true,
  },
  {
    name: "Flux Point Studios",
    logo: "/ecosystem/flux-point-studios.png",
    logoLight: "/ecosystem/flux-point-studios.png",
    width: 250,
    height: 274,
    tone: "dark",
    logoShape: "icon",
    showName: true,
  },
  {
    name: "FluidTokens",
    logo: "/ecosystem/fluidtokens.svg",
    logoLight: "/ecosystem/fluidtokens-dark.svg",
    width: 187,
    height: 230,
    tone: "dark",
    logoShape: "icon",
    showName: true,
  },
  {
    name: "Indigo Labs",
    logo: "/ecosystem/indigo-labs.png",
    logoLight: "/ecosystem/indigo-labs.png",
    width: 1500,
    height: 500,
    tone: "dark",
    logoShape: "wide",
    monochromeOnLight: true,
  },
  {
    name: "Strike Finance",
    logo: "/ecosystem/strike-finance.svg",
    logoLight: "/ecosystem/strike-finance.svg",
    width: 356,
    height: 51,
    tone: "dark",
    logoShape: "wide",
    monochromeOnLight: true,
  },
  {
    name: "Artifi Labs",
    logo: "/ecosystem/artifi-labs.svg",
    logoLight: "/ecosystem/artifi-labs-light.svg",
    width: 122,
    height: 31,
    tone: "dark",
    logoShape: "wide",
  },
  {
    name: "Lace Wallet",
    logo: "/ecosystem/lace-wordmark.svg",
    logoLight: "/ecosystem/lace-wordmark-light.svg",
    width: 105,
    height: 35,
    tone: "dark",
    logoShape: "wide",
  },
  {
    name: "Liqwid",
    logo: "/ecosystem/liqwid.svg",
    logoLight: "/ecosystem/liqwid-light.svg",
    width: 2652,
    height: 841,
    tone: "dark",
    logoShape: "wide",
  },
  {
    name: "Midnight",
    logo: "/ecosystem/midnight-logo-light.svg",
    logoLight: "/ecosystem/midnight-logo-dark.svg",
    width: 251,
    height: 55,
    tone: "dark",
    logoShape: "wide",
  },
  {
    name: "Minswap",
    logo: "/ecosystem/minswap.png",
    logoLight: "/ecosystem/minswap-dark.png",
    width: 96,
    height: 96,
    tone: "dark",
    logoShape: "icon",
    showName: true,
  },
  {
    name: "Modus Create",
    logo: "/ecosystem/modus-create.svg",
    logoLight: "/ecosystem/modus-create.svg",
    width: 186,
    height: 24,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Pogun",
    logo: "/ecosystem/pogun-wordmark.svg",
    logoLight: "/ecosystem/pogun-wordmark-light.svg",
    width: 800,
    height: 215,
    tone: "dark",
    logoShape: "wide",
  },
  {
    name: "RealFi",
    logo: "/ecosystem/realfi-logo.svg",
    logoLight: "/ecosystem/realfi-logo-dark-text.svg",
    width: 346,
    height: 112,
    tone: "dark",
    logoShape: "wide",
  },
  {
    name: "Tweag",
    logo: "/ecosystem/tweag.png",
    logoLight: "/ecosystem/tweag-light.png",
    width: 2110,
    height: 570,
    tone: "dark",
    logoShape: "wide",
  },
  {
    name: "USDCx",
    logo: "/ecosystem/usdcx.png",
    logoLight: "/ecosystem/usdcx.png",
    width: 330,
    height: 331,
    tone: "dark",
    logoShape: "icon",
    showName: true,
  },
  {
    name: "WingRiders",
    logo: "/ecosystem/wingriders.svg",
    logoLight: "/ecosystem/wingriders-dark.svg",
    width: 1600,
    height: 309,
    tone: "dark",
    logoShape: "wide",
  },
] as const;
