export type EcosystemPartner = {
  name: string;
  logo: string;
  logoLight?: string;
  width: number;
  height: number;
  tone: "dark" | "light";
  logoShape?: "wide" | "icon" | "tall";
};

export const ECOSYSTEM_PARTNERS: readonly EcosystemPartner[] = [
  {
    name: "Anastasia Labs",
    logo: "/ecosystem/anastasia-labs.svg",
    logoLight: "/ecosystem/anastasia-labs.svg",
    width: 2000,
    height: 464,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Artifi Labs",
    logo: "/ecosystem/artifi-labs.svg",
    logoLight: "/ecosystem/artifi-labs-light.svg",
    width: 122,
    height: 31,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Input Output Global",
    logo: "/ecosystem/input-output.svg",
    logoLight: "/ecosystem/input-output-light.svg",
    width: 240,
    height: 31,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Lace Wallet",
    logo: "/ecosystem/lace-wordmark.svg",
    logoLight: "/ecosystem/lace-wordmark-light.svg",
    width: 105,
    height: 35,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Liqwid",
    logo: "/ecosystem/liqwid.svg",
    logoLight: "/ecosystem/liqwid-light.svg",
    width: 2652,
    height: 841,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Midgard",
    logo: "/midgard-logo.png",
    logoLight: "/midgard-logo-light.png",
    width: 1092,
    height: 251,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Midnight",
    logo: "/ecosystem/midnight-logo-light.svg",
    logoLight: "/ecosystem/midnight-logo-dark.svg",
    width: 251,
    height: 55,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Minswap",
    logo: "/ecosystem/minswap.png",
    logoLight: "/ecosystem/minswap-dark.png",
    width: 96,
    height: 96,
    tone: "light",
    logoShape: "icon",
  },
  {
    name: "Modus Create",
    logo: "/ecosystem/modus-create.svg",
    logoLight: "/ecosystem/modus-create.svg",
    width: 186,
    height: 24,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Pogun",
    logo: "/ecosystem/pogun-wordmark.svg",
    logoLight: "/ecosystem/pogun-wordmark-light.svg",
    width: 800,
    height: 215,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "RealFi",
    logo: "/ecosystem/realfi-logo.svg",
    logoLight: "/ecosystem/realfi-logo-dark-text.svg",
    width: 346,
    height: 112,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Sundae Labs",
    logo: "/ecosystem/sundae-labs-dark.png",
    logoLight: "/ecosystem/sundae-labs.png",
    width: 1143,
    height: 195,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "Tweag",
    logo: "/ecosystem/tweag.png",
    logoLight: "/ecosystem/tweag-light.png",
    width: 2110,
    height: 570,
    tone: "light",
    logoShape: "wide",
  },
  {
    name: "USDCx",
    logo: "/ecosystem/usdcx.png",
    logoLight: "/ecosystem/usdcx.png",
    width: 330,
    height: 331,
    tone: "light",
    logoShape: "icon",
  },
  {
    name: "WingRiders",
    logo: "/ecosystem/wingriders.svg",
    logoLight: "/ecosystem/wingriders-dark.svg",
    width: 1600,
    height: 309,
    tone: "light",
    logoShape: "wide",
  },
] as const;
